#! /bin/sh

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
$HOME/.config/bspwm/laptop_output_dual_monitor 

sxhkd &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
dunst &
nitrogen --restore
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
pgrep bspswallow || $HOME/.config/bspwm/bspswallow &

bspc monitor HDMI2 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

